run:
  timeout: 10m
  allow-serial-runners: true

linters-settings:
  goimports:
    local-prefixes: github.com/theopenlane/echox
  gofumpt:
    extra-rules: true
  gosec:
    exclude-generated: true
  revive:
    ignore-generated-header: true

linters:
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - govet
    - gosec
    - ineffassign
    - misspell
    - noctx
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unused
    - whitespace
    - wsl
issues:
  fix: true
  exclude-use-default: true
  exclude-dirs:
    - _fixture/*
    - .buildkite/*
    - .github/*
  exclude-files:
    - _test.go
